apiVersion: v1
kind: Service
metadata:
  name: redmine
#  namespace: services
  labels:
    app: redmine
spec:
  ports:
  - name: redmine-web
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30180
  selector:
    app: redmine
  type: NodePort    

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-claim
  labels:
    app: redmine
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
#  namespace: services
  labels:
    app: redmine
spec:
  strategy:
    type: Recreate
#  replicas: 1
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - image: sameersbn/redmine:3.4.6
        imagePullPolicy: IfNotPresent
        name: redmine
        env:
        - name: DB_ADAPTER
          value: "mysql2"
        - name: DB_HOST
          value: "mysql"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "redmine"
        - name: DB_PASS
          value: "password"
        - name: DB_NAME
          value: "redmine_production"
#        - name: REDMINE_PORT
#          value: "80"
#        - name: REDMINE_HTTPS
#          value: "false"
#        - name: REDMINE_SUDO_MODE_ENABLED
#          value: "false"
        ports:
        - containerPort: 30180

        volumeMounts:
            - name: redmine
              mountPath: /home/redmine/data
      volumes:
        - name: redmine
          persistentVolumeClaim:
            claimName: redmine-claim

#      restartPolicy: Always
status: {}
