apiVersion: v1
kind: Service
metadata:
  name: openldap
  labels:
    app: openldap

spec:
  ports:
    - port: 389
      targetPort: 389
  selector:
    app: openldap
  type: NodePort
	
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openldap
  labels:
    app: openldap
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openldap
    spec:
      initContainers:
        - name: init-copy
          image: busybox
          command: ['sh','-c','cp /config-map/* /config-storage; ls -lrt /config-storage']
          volumeMounts:
          - name: openldap-seedusers
            mountPath: /config-map
          - name: config-storage
            mountPath: /config-storage
      containers:
        - name: openldap
          image: osixia/openldap:1.1.10
          args: ["--loglevel", "debug"]
          volumeMounts:
            - name: config-storage
              mountPath: /container/service/slapd/assets/config/bootstrap/ldif/custom
            - name: ldap-certs
              mountPath: /container/service/slapd/assets/certs
          ports:
            - containerPort: 389
            - containerPort: 636
          env:
            - name: LDAP_LOG_LEVEL
              value: "256"
            - name: LDAP_ORGANISATION
              value: "Example Inc."
            - name: LDAP_DOMAIN
              value: "local.io"
            - name: LDAP_ADMIN_PASSWORD
              value: "admin"
            - name: LDAP_REMOVE_CONFIG_AFTER_SETUP
              value: "false"

      volumes:
        - name: config-storage
          emptyDir: {}
        - name: ldap-certs
          hostPath:
            path: "/data/ldap/certs"
        - name: openldap-seedusers
          configMap:
            name: openldap-seedusers
